before:
  hooks:
    - go mod tidy
builds:
  - binary: serve
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}
dockers:
  - image_templates:
      - "ghcr.io/tschaub/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/tschaub/{{ .ProjectName }}:v{{ .Major }}"
    build_flag_templates:
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.url=https://github.com/tschaub/{{ .ProjectName }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github-native
